pipeline_template: ci/modules/Jenkinsfile-integration-tests
run_flake: "true"
mypy_mode: "report"
credentials:
  - type: "usernamePassword"
    credentialsId: "aws-jenkins-user"
    usernameVariable: "TEST_USR"
    passwordVariable: "TEST_PWD"
