pipeline_template: ci/modules/Jenkinsfile-integration-tests
run_flake: "true"
mypy_mode: "report"
credentials:
  - type: "usernamePassword"
    credentialsId: "jenkins_on_openstack"
    usernameVariable: "AWS_ACCESS_KEY_ID"
    passwordVariable: "AWS_SECRET_ACCESS_KEY"
  - type: "usernamePassword"
    credentialsId: "aws-jenkins-user"
    usernameVariable: "TEST_USR"
    passwordVariable: "TEST_PWD"
